name: majadigi
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.4  # Menambahkan dependensi untuk gambar SVG
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  csv: ^8.0.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/Splash Screen.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/onboarding4.png
    - assets/images/logo.png
    - assets/images/languange_icon.png
    - assets/images/email_verification.png
    - assets/images/forgot_password_mail.png
    - assets/images/email_sent_icon.png
    - assets/images/personalization_location_map.png
    - assets/data/jatim_kecamatan.csv
    - assets/images/feature_mobilitas.png
    - assets/images/feature_ekonomi.png
    - assets/images/feature_pekerjaan.png
    - assets/images/feature_kesehatan.png
    - assets/images/feature_sosial.png
    - assets/images/feature_pemerintahan.png
    - assets/images/feature_keamanan.png
    - assets/images/personalization_success.png
    - assets/images/header_texture.png
    - assets/images/dapurmbg.png
    - assets/images/ayopasok.png
    - assets/images/avatar_placeholder.png
    - assets/images/layanan_bapenda.png
    - assets/images/layanan_rsud.png
    - assets/images/layanan_transportasi.png
    - assets/images/layanan_siskaperbapo.png
    - assets/images/layanan_nomor_darurat.png
    - assets/images/artikel_1.png
    - assets/images/artikel_2.png
    - assets/images/artikel_3.png
    - assets/data/kendaraan_dummy.csv
    - assets/data/njkb_database.csv
    - assets/data/kamar_rsud.csv
    - assets/data/jadwal_operasi.csv
    - assets/data/info_antrean.csv
    - assets/data/kamar_saiful_anwar.csv
    - assets/data/jadwal_saiful_anwar.csv
    - assets/data/antrean_saiful_anwar.csv
    - assets/data/kamar_karsa_husada.csv
    - assets/data/jadwal_karsa_husada.csv
    - assets/data/antrean_karsa_husada.csv
    - assets/data/kamar_prov_jatim.csv
    - assets/data/jadwal_prov_jatim.csv
    - assets/data/antrean_prov_jatim.csv
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700

  uses-material-design: true