// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzY1CyZmoVhC6BUP3QJ1s3kLFNVmhgSfQ',
    appId: '1:439586155937:web:6883dc02273defb52eefe0',
    messagingSenderId: '439586155937',
    projectId: 'capstone-majadigi',
    authDomain: 'capstone-majadigi.firebaseapp.com',
    storageBucket: 'capstone-majadigi.firebasestorage.app',
    measurementId: 'G-XY4KF08XZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkmT3SqXKeIdgTQgHw6w1EcUIKNMwWkOA',
    appId: '1:439586155937:android:3add3655ec9f30002eefe0',
    messagingSenderId: '439586155937',
    projectId: 'capstone-majadigi',
    storageBucket: 'capstone-majadigi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEXrFHbbOSlvGaLcFjY1rPpHFT9tkL5JY',
    appId: '1:439586155937:ios:2d917e27ac0f5fee2eefe0',
    messagingSenderId: '439586155937',
    projectId: 'capstone-majadigi',
    storageBucket: 'capstone-majadigi.firebasestorage.app',
    iosBundleId: 'com.example.capstonemajadigi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEXrFHbbOSlvGaLcFjY1rPpHFT9tkL5JY',
    appId: '1:439586155937:ios:2d917e27ac0f5fee2eefe0',
    messagingSenderId: '439586155937',
    projectId: 'capstone-majadigi',
    storageBucket: 'capstone-majadigi.firebasestorage.app',
    iosBundleId: 'com.example.capstonemajadigi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzY1CyZmoVhC6BUP3QJ1s3kLFNVmhgSfQ',
    appId: '1:439586155937:web:e6c2ab8168e7a4cc2eefe0',
    messagingSenderId: '439586155937',
    projectId: 'capstone-majadigi',
    authDomain: 'capstone-majadigi.firebaseapp.com',
    storageBucket: 'capstone-majadigi.firebasestorage.app',
    measurementId: 'G-DEZ31473JH',
  );
}
